apiVersion: v2
name: insurancestack
description: A Helm chart for InsuranceStack application
type: application
version: 0.1.0
appVersion: "1.0.0"
keywords:
  - insurancestack
  - insurance
  - cloudbees
  - feature-management
maintainers:
  - name: InsuranceStack Team
